### ISSUE TITLE
Places block, not plane

### ISSUE THREAD

**Issue by boxedsarcasm** [legofreak107/VehiclesPlus#1]
hi, im not sure if Im doing something wrong, but when I place the plane it just turns into a block, i have the texture pack. Thanks

**Comment by legofreak107** [comment]
Can you please give me more info such as error codes, version etc? Thanks!

**Comment by boxedsarcasm** [comment]
Im not sure where to get error codes (It boots fine) an im on spigot 1.12.2 I was messing with it and if I hit the block with another plane (block) it places. I will try to record a video (my pc is awful so I might not be able to) Thank you

**Comment by boxedsarcasm** [comment]
okay, i tried to record it and it just crashed my game, sorry :( 

I didnt try it in survival until today and that seemed to fix it.

Im not sure if I should open a new issue or not, but the plane and helicopter dont leave the ground

**Comment by legofreak107** [comment]
I am updating the plugin rn. And please message me on spigot. I am online there a lot more :)

**Comment by boxedsarcasm** [comment]
okay, thank you so much for your time :)
